### ISSUE TITLE
Full Application Tests (Optional)

### ISSUE THREAD

**Issue by ealmloffku** [KU-EECS-384-group-R6/Truthy#12]
It might be nice to introduce a system test that [fuzzes](https://en.wikipedia.org/wiki/Fuzzing) the whole program to make sure valid expressions evaluate to a value without causing any errors if we have time

**Comment by mitch680l** [comment]
I'm pretty sure I have done this.

**Comment by ealmloffku** [comment]
This looks done to me 🙂. Fuzzing is slightly different, but what we have implement works too
